module.exports = {
  SERVER: {
    PORT: 3000,
  },
  PAGES: {
    GENERAL: 'GENERAL',
    CREATE_POST: 'CREATE_POST',
    DRAFT: 'DRAFT',
    WAITING: 'WAITING',
    REJECT: 'REJECT',
    PUBLISHED: 'PUBLISHED',
    USER: 'USER',
    CATEGORY: 'CATEGORY',
    TAG: 'TAG',
  },
  USER_ROLES: {
    SUBSCRIBER: 'SUBSCRIBER',
    WRITER: 'WRITER',
    EDITOR: 'EDITOR',
    ADMIN: 'ADMIN',
  }
}